###############################################################################
# buildPolicy.yml
#
# Description
#   This playbook is used to assist in the creation of new AT-TLS rules to 
#   encrypt traffic to/from z/OS. It does not update the live file, instead 
#   generating the policy in a new file to be validated by the user before 
#   incorporation into the master file.
# 
# Required files
#   - vars/common.yml
#   Contains common variables related to your configuration of the Policy 
#   Agent, typically located in SYS1.TCPPARMS(PAGENT**).
#     
# Authors
#   Caleb Adra
#   cadra@ibm.com
#   February 2026
#
# No warranty implied
###############################################################################

---

- hosts: zos_host

  collections:
    - ibm.ibm_zos_core
    - ansible.builtin
    - ansible.community.general

  environment: "{{ environment_vars }}"

  vars_files:
    - ../vars/policy.yml

  gather_facts: no
  
  tasks:
  - name: Generate AT-TLS Policy
    template:
      src: policyTemplate.j2
      dest: "/tmp/{{ rule_name }}_policy.conf"
      mode: "0755"
    register: generate_policy